services:
  foyer:
    container_name: foyer
    image: wissem1717/springboot-app:v1.0.0  # Use the image from your Docker Hub
    ports:
      - "8088:8088"  # Map port 8089 (as specified in your Spring Boot properties)
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCom     
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root  # Set the password for MySQL
    restart: unless-stopped
    depends_on:
      - dbmysql

  dbmysql:
    image: "mysql:5.7"
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foyer  # Use your database name
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql  # Persistent storage for MySQL

volumes:
  db:  # Declare a volume for MySQL data
